These are my experiments while learning the [[http://clojure.org][Clojure]] programming language.

- This uses Leiningen from http://leiningen.org/

Useful links:

- A Clojure cheat sheet: [[http://clojure.org/cheatsheet]]
- Clojure For The Brave and True: [[http://www.braveclojure.com]]
- Clojure From The Ground Up: [[http://aphyr.com/posts/301-clojure-from-the-ground-up-welcome]]
- Clojure - Functional Programming for the JVM: [[http://java.ociweb.com/mark/clojure/article.html]]
- ClojureDocs - Community-Powered Clojure Documentation and Examples: [[http://clojuredocs.org]]

* 01-hello-world

This demonstrates how to stand up an empty new Clojure project.

You can make the first project by:

#+BEGIN_SRC sh
lein new app hello-world
mv hello-world 01-hello-world
#+END_SRC

The default project from Leiningen actaully is a hello world app, so just run it, you don't need to write any code.

#+BEGIN_SRC sh
lein run
#+END_SRC

If you want to make a .jar file of the project that you can distribute, then run the following:

#+BEGIN_SRC sh
lein uberjar
#+END_SRC

After that, there will be a file 01-hello-world/target/hello-world-0.1.0-SNAPSHOT-standalone.jar

* 02-user-input

This demonstrates getting input from the user and doing something with it.  The
file you are most interested in is src/user_input/core.clj

* 03-gui-button

We make a simple GUI using the [[https://github.com/daveray/seesaw][Seesaw]] library with just one button, a "quit" button.

Note that we added a dependency for Seesaw to the file project.clj.
